---
- name: Open firewall for kubernetes ports
  become: yes
  become_user: root
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - 6443/tcp
    - 2379/tcp
    - 2380/tcp
  tags:
    - firewall
